import type { Metadata } from 'next'
import './style.css'
import {Rubik_Bubbles} from 'next/font/google'
  
export const rubik = Rubik_Bubbles({
  subsets: ['latin'],
  weight : '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <title>
        Página inicial jogo da Velha
      </title>
      <body className={rubik.className}>{children}</body>
    </html>
  )
}
