import type { Metadata } from 'next'
import { Rubik_Bubbles } from 'next/font/google'
import './globals.css'

const rubik = Rubik_Bubbles({ 
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <title>
        Jogo da Velha
      </title>
      <body className={rubik.className}>{children}</body>
    </html>
  )
}
